easy_admin:
    site_name: "Clap'Sabots"
    list:
        max_results: 100
    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y H:i:s'
    
    design:
        templates: 
            label_null: 'easy_admin/label_null.html.twig'
        menu:
            - label: 'Administration'
              children: ['Club', 'ClubYear', 'Section']
            - label: 'Membres'
              children: ['Member']
            - label: 'Costumes'
              children:
                - { entity: 'ClothesType', label: 'Types' }
                - { entity: 'ClothesOpportunity', label: 'Opportunity' }
                - { entity: 'ClothesSeason', label: 'Seasons' }
                - { entity: 'ClothesTexture', label: 'Textures' }
                - { entity: 'ClothesTypeZone', label: 'Zones' }
    entities:
        Club:
            class: App\Entity\Club
            form:
                fields: 
                    - { type: group, label: General, column: 6, icon: edit }
                    - { property: name }
                    - { property: vatNumber }
                    - { type: group, label: Address, column: 6 }
                    - { property: headOfficeAddress, label: '', type: 'App\Form\Type\AddressType'  } 
                    - { type: group, label: Years, icon: calendar }
                    - { property: clubYears, label: '', type: embedded_list }
        Address: 
            class: App\Entity\Address
        ClubYear: 
            class: App\Entity\ClubYear 
        Section: 
            class: App\Entity\Section
            form:
                fields: 
                    - { type: 'tab' , label: 'Section Information', icon: 'edit' }
                    - { property: name }
                    - { property: code }
                    - { type: 'tab' , label: 'Affiliate list', icon: 'user' }
                    - { property: memberShips, label: '', type: embedded_list }
        ClothesColor:
            class: App\Entity\ClothesColor
            list:
                sort: ['name', 'ASC']
                fields:
                    - { property: id }
                    - { property: name }
                    - { property: code, template: 'easy_admin/property_color.html.twig' }
            form:
                fields:
                    - { property: name }
                    - { property: code, type: 'App\Form\Type\ColorType'  }
        ClothesType:
            class: App\Entity\ClothesType
            list:
                sort: ['type', 'ASC']
            form:
                fields:
                    - { property: name }
                    - { property: type }
                    - { property: zone }
        ClothesTypeType:
            class: App\Entity\ClothesTypeType
            form:
                fields:
                    - { property: name }
        ClothesOpportunity:
            class: App\Entity\ClothesOpportunity
            list:
                sort: ['name', 'ASC']
        ClothesTypeZone:
            class: App\Entity\ClothesTypeZone
            list:
                sort: ['name', 'ASC']
            form:
                fields:
                    - { property: name }
        ClothesTexture:
            class: App\Entity\ClothesTexture
            list:
                sort: ['name', 'ASC']
            form:
                fields:
                    - { property: name }
        ClothesSeason:
            class: App\Entity\ClothesSeason
            list:
                sort: ['name', 'ASC']
            form:
                fields:
                    - { property: name }
        Member:
            class: App\Entity\Member
            list:
                sort: ['lastname', 'ASC']
            form:
                fields:
                    - { type: 'tab' , label: 'Account Information', icon: 'user' }
                    - { type: group, label: General, columns: 6, icon: edit }
                    - { property: firstname }
                    - { property: lastname }
                    - { property: email, type: email }
                    - { property: phone }
                    - { property: mobilePhone }
                    - { property: 'sex', type: 'App\Form\Type\SexType' }
                    - { property: 'birthdate', type: 'App\Form\Type\BirthdateType' }
                    - { property: niss }
                    - { property: 'insurer', type: 'App\Form\Type\InsurerType' }
                    - { type: group, label: Address, columns: 6 }
                    - { property: 'address', type: 'App\Form\Type\AddressType' }
                    - { type: 'tab' , label: 'Affiliate', icon: 'user' }
                    - { property: memberShips, type: embedded_list }
        MemberShip:
            class: App\Entity\MemberShip
